import { test, expect } from '@playwright/test'
import { execFileSync, spawnSync } from 'node:child_process'
import { existsSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { launchApp, newProject, importAndPlaceMedia, invokeCmd, tmpDir } from './helpers/driver'

// Runtime verification for the Standard (ffmpeg) engine's HARDWARE decode
// lanes — the sibling of preview-sw-conformance.spec.ts, but for the HW paths.
// It proves that the real app decodes an INTERFRAME 8-bit H.264 clip
// end-to-end through a hardware lane and that the rendered preview frame is
// correct (SSIM vs an ffmpeg reference of the same source frame). Two
// transport shapes share this one spec:
//   - nvdec/vaapi (Linux) and videotoolbox (macOS, issue #10) copy-back:
//     NV12 copies back to system memory and rides the SAME previewSw
//     transport as software (ADR 0034), so everything downstream
//     (ring → Nv12Ingest → sprite) is shared.
//   - d3d11va (Windows shared-texture): frames stay on the GPU; native
//     converts NV12→RGBA with its own shader and shares the texture
//     (GpuTransport). SSIM here is the lane's natural-content structural
//     gate; the matrix/range correctness gate is preview-hw-color.spec.ts.
// Either way `Compositor.activeClipProbe` reports `sourceKind: "native-gpu"`.
//
// PARAMETERIZED BY VARIANT = HW LANE × FIXTURE. One test() per VARIANTS entry;
// each launches the app with WEFTCUT_FORCE_HW_LANE=<lane>, which pins main's
// `decodeCap:probeHw` resolver to consider ONLY that HW lane (plus the software
// fallback). A variant SKIPS CLEANLY when its lane didn't engage on this
// machine — e.g. when the addon never advertised the lane, the resolver finds
// no candidate and falls back to software, so `probe.hwLane === null` and the
// test skips rather than failing.
// This lets the ONE spec run correctly on a box that has NVDEC but not VAAPI
// (or a Mac, which has only videotoolbox) with no per-machine config. The loop
// body is variant-agnostic — fixture, artifact names, and the forced lane all
// come from the entry — so a new codec on an existing lane (e.g. the
// videotoolbox ProRes/p10 variant, VT lane ticket 03) is one more entry.
//
// Fixture (8-bit 1080p30 H.264, interframe, HW-decodable on every lane):
// test_1080p_h264.mp4, the `h264Interframe` entry of the fixture matrix
// (fixtures/generate-fixtures.mjs) — gitignored, auto-generated by the
// Playwright globalSetup like all media fixtures.
// (The 10-bit test_1080p_gradient10_h264.mp4 is NOT usable: H.264 High10 isn't
// NVDEC-decodable.)
//
// Model: e2e/electron/preview-sw-conformance.spec.ts. Requires a
// VITE_WEFTCUT_E2E=1 build (the __weftcutTest hook surface) and the current
// native-decode addon (advertising the HW lane under test).

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const MEDIA_DIR = process.env.WEFTCUT_TEST_MEDIA || path.resolve(__dirname, '../fixtures/media')
const H264 = path.resolve(MEDIA_DIR, 'test_1080p_h264.mp4')
// 10-bit fixtures for the videotoolbox p10 variants (VT lane ticket 03). Both
// 1080p30, ≥ 1 s, already in the generator matrix. The SSIM leg normalizes
// BOTH sides through `format=yuv420p`, so a 10-bit source works unmodified as
// a structural gate.
// - ProRes 422 HQ (yuv422p10le): the codec the lane exists for. testsrc2
//   content like the H.264 fixture, so it shares SSIM_FLOOR_HIGH_FREQ. ffmpeg's
//   VT hwaccel REQUIREs the hardware ProRes decoder (release/8.x), which only
//   ProRes-engine chips carry (M1 Pro/Max, M2+) — on a base M1 the probe
//   declines and this variant SKIPS cleanly (software fallback proven by the
//   skip path itself).
// - HEVC Main10 (yuv420p10le): the smooth-gradient fixture (SSIM_FLOOR_SMOOTH).
//   Hardware-decoded by every Apple Silicon media block, so the I420P10
//   transport → ten-bit ingest path gates GREEN on any Mac host, ProRes engine
//   or not.
const PRORES = path.resolve(MEDIA_DIR, 'test_1080p_30fps_prores.mov')
const HEVC10 = path.resolve(MEDIA_DIR, 'test_1080p_gradient10.mp4')

// Composition + probe target. 500 ms @30 fps = source frame 15; the clip is
// placed 1:1 at t=0, so composition-time 500 ms maps to source frame 15 exactly.
// Shared across variants — every VARIANTS fixture is 1080p30, ≥ 1 s.
const CANVAS = { width: 1920, height: 1080, fpsNum: 30, fpsDen: 1 }
const SEEK_US = 500_000
const FRAME_IDX = Math.round((SEEK_US * CANVAS.fpsNum) / (1_000_000 * CANVAS.fpsDen))
// SSIM floors, per FIXTURE rather than per lane: how high the score can reach
// is a property of the content being compared, not of the decoder under test.
// H.264/HEVC decode is bit-exact by specification, so the gate does not measure
// decode correctness — the score is spent entirely downstream, where our ingest
// shader upsamples the chroma plane through the GPU's texture sampler while the
// ffmpeg reference upsamples it through swscale. Two different algorithms, so a
// correct frame never scores 1.0; and sampler sub-texel precision is
// implementation-defined, so the exact value carries a machine fingerprint.
// The floors are set from what a CORRECT decode actually scores, with headroom
// for the next GPU; a garbage decode still matches NONE of the three candidate
// frames (see the neighbor-frame note at the comparison). Raise one only with
// measurements from MORE THAN ONE machine — a floor tuned to a single box
// lands inside the machine-to-machine spread and flips the same correct decode
// between pass and fail.
/// testsrc2: dense high-frequency synthetic detail, which maximizes the
/// chroma-upsampling disagreement. Correct decodes measured 0.9794–0.982.
const SSIM_FLOOR_HIGH_FREQ = 0.96
/// Smooth gradient content, where the two upsamplers barely disagree at all.
/// A correct decode measured 0.997468 — this floor still has real headroom.
const SSIM_FLOOR_SMOOTH = 0.98

// Skip-path audit seam: an OUTER `WEFTCUT_FORCE_HW_LANE` (exported around the
// runner by an operator) overrides every variant's own pin. Pinning a lane the
// box does not advertise makes main's `decodeCap:probeHw` hide all HW lanes,
// so EVERY variant must then report SKIP (hwLane === null), never FAIL — a
// one-command proof of the clean-skip degradation on a machine whose own lane
// would otherwise engage (e.g. WEFTCUT_FORCE_HW_LANE=vaapi on a videotoolbox
// Mac). Unset — the normal run — each variant pins its own lane. (The
// override has to live HERE: launchApp spreads the spec's env LAST, so the
// outer variable can never reach the app around this spec on its own.)
const OUTER_LANE_PIN = process.env.WEFTCUT_FORCE_HW_LANE

// One test() per variant: a hardware lane × the fixture (codec) it must
// decode. `id` keys artifacts and log lines (a lane can host several codec
// variants); `codec` names the clip in the title.
interface HwVariant {
  lane: 'nvdec' | 'vaapi' | 'd3d11va' | 'videotoolbox'
  id: string
  codec: string
  fixture: string
  /// Which ingest path the bound frame must have taken (`ActiveClipProbe.
  /// boundFrameKind`): copy-back 8-bit ships NV12 → Nv12Ingest; copy-back
  /// 10-bit ships I420P10 → TenBitIngest ('p10', VT lane ticket 03); the
  /// Windows shared-texture lane binds an ImageBitmap snapshot ('browser').
  frameKind: 'nv12' | 'p10' | 'browser'
  /// Floor the best-of-three SSIM must clear. Tracks `fixture`, never the
  /// lane — see the SSIM_FLOOR_* notes.
  ssimFloor: number
}
const VARIANTS: readonly HwVariant[] = [
  { lane: 'nvdec', id: 'nvdec-h264', codec: 'H.264', fixture: H264, frameKind: 'nv12', ssimFloor: SSIM_FLOOR_HIGH_FREQ },
  { lane: 'vaapi', id: 'vaapi-h264', codec: 'H.264', fixture: H264, frameKind: 'nv12', ssimFloor: SSIM_FLOOR_HIGH_FREQ },
  { lane: 'd3d11va', id: 'd3d11va-h264', codec: 'H.264', fixture: H264, frameKind: 'browser', ssimFloor: SSIM_FLOOR_HIGH_FREQ },
  { lane: 'videotoolbox', id: 'videotoolbox-h264', codec: 'H.264', fixture: H264, frameKind: 'nv12', ssimFloor: SSIM_FLOOR_HIGH_FREQ },
  // VT lane ticket 03 — the I420P10 preview transport variants (see the
  // fixture notes above for which hosts each engages on).
  { lane: 'videotoolbox', id: 'videotoolbox-prores', codec: 'ProRes', fixture: PRORES, frameKind: 'p10', ssimFloor: SSIM_FLOOR_HIGH_FREQ },
  { lane: 'videotoolbox', id: 'videotoolbox-hevc10', codec: 'HEVC Main10', fixture: HEVC10, frameKind: 'p10', ssimFloor: SSIM_FLOOR_SMOOTH },
]

/// ffmpeg binary: honor an explicit `FFMPEG` override, else rely on PATH.
/// Returns null when ffmpeg can't be executed at all, so the SSIM step degrades
/// to a warning rather than a false failure (the lane-engaged assertion stands).
function ffmpegBin(): string | null {
  const cand = process.env.FFMPEG || 'ffmpeg'
  const r = spawnSync(cand, ['-version'], { encoding: 'utf8' })
  return r.status === 0 ? cand : null
}

/// Parse ffmpeg's `ssim` filter log line: `... All:0.987654 (18.9)`.
function parseSsimAll(stderr: string): number | null {
  const m = stderr.match(/All:\s*([0-9]*\.?[0-9]+)/)
  return m ? Number(m[1]) : null
}

/// Which transport the title names. Derived from `frameKind` rather than listed
/// per lane: 'browser' IS the shared-texture shape (d3d11va binds an
/// ImageBitmap snapshot), everything else copies back into NV12/I420P10 ship
/// bytes (ADR 0034). A hardcoded "copy-back" for all four contradicted this
/// file's own header on the one lane that isn't.
const transportWord = (frameKind: HwVariant['frameKind']) =>
  frameKind === 'browser' ? 'shared-texture' : 'copy-back'

for (const { lane, id, codec, fixture, frameKind, ssimFloor } of VARIANTS) {
  test(`preview-hw: ffmpeg engine decodes interframe ${codec} on the ${lane} ${transportWord(frameKind)} lane + SSIM (issue #5 Block C3) @serial`, async () => {
    test.skip(!existsSync(fixture), `${codec} fixture not found at ${fixture} (set WEFTCUT_TEST_MEDIA)`)
    test.setTimeout(240_000)
    const PROJECT_PARENT = tmpDir('weftcut-e2e-preview-hw-proj-')
    const OUT_DIR = tmpDir('weftcut-e2e-preview-hw-')

    // Force the resolver to only consider THIS hardware lane (+ software
    // fallback). On a box that doesn't advertise the lane, the resolver finds no
    // candidate and falls back to software → probe.hwLane === null → clean skip.
    // An operator's OUTER pin (skip-path audit, see OUTER_LANE_PIN) wins.
    const { app, page } = await launchApp({ env: { WEFTCUT_FORCE_HW_LANE: OUTER_LANE_PIN ?? lane } })
    // Surface renderer console noise (errors are findings for the investigation).
    const consoleLines: string[] = []
    page.on('console', (m) => consoleLines.push(`[${m.type()}] ${m.text()}`))
    page.on('pageerror', (e) => consoleLines.push(`[pageerror] ${String(e)}`))

    let toggledOn = false
    try {
      await newProject(page, {
        parentFolder: PROJECT_PARENT,
        name: 'preview-hw-' + id + '-' + Date.now(),
        canvas: CANVAS,
      })

      // ── Pin the ffmpeg (Standard) engine *before* placing the layer ─────────
      // Engine resolution reads `decode_engine` live at acquire
      // (PixiPreview.resolveSource), so it must be set before the clip is first
      // composited. With `decode_engine: 'ffmpeg'` pinned, `resolveSource` builds
      // a `FfmpegSource` for ANY source by path — h264 is NOT a blind-spot
      // format, so there is NO native-sw route to wait for (that gate is
      // ProRes-specific); the ffmpeg pin alone routes h264 to FfmpegSource.
      const after = (await invokeCmd(page, 'app_settings_set', {
        patch: { decode_engine: 'ffmpeg' },
      })) as { decode_engine: string }
      expect(after.decode_engine).toBe('ffmpeg')
      toggledOn = true

      // ── Import + place the variant's clip ───────────────────────────────────
      const { layerId, kind } = await importAndPlaceMedia(page, { mediaAbsPath: fixture })
      expect(kind).toBe('Video')

      // Ensure the PixiPreview bridge is registered (activeClipProbe throws until
      // it is) before we drive a seek.
      await page.waitForFunction(
        () => {
          try {
            ;(window as { __weftcutTest: { activeClipProbe(id?: string): unknown } }).__weftcutTest.activeClipProbe()
            return true
          } catch {
            return false
          }
        },
        undefined,
        { timeout: 30_000, polling: 250 },
      )

      // Seek ONCE into the clip; poll read-only until the ring holds the SEEKED
      // frame bound to the sprite. Accept either HW (`native-gpu`) or the
      // software fallback (`sw`) here — the fallback is the clean-skip case, sorted
      // out below by inspecting `hwLane`.
      await page.evaluate(
        (us) => (window as { __weftcutTest: { weftcutSeekUs(us: number): void } }).__weftcutTest.weftcutSeekUs(us),
        SEEK_US,
      )

      const handle = await page.waitForFunction(
        ([id, target]) => {
          const p = (window as { __weftcutTest: { activeClipProbe(id?: string): {
            sourceKind: string
            hwLane: string | null
            ringLastPtsUs: number | null
            spriteBound: boolean
            spriteWidth: number
            spriteHeight: number
            boundFrameKind: string | null
          } | null } }).__weftcutTest.activeClipProbe(id)
          if (!p) return null
          if (p.sourceKind !== 'native-gpu' && p.sourceKind !== 'sw') return null
          if (p.ringLastPtsUs == null || p.ringLastPtsUs < target) return null
          if (!p.spriteBound) return null
          return p
        },
        [layerId, SEEK_US] as const,
        { timeout: 90_000, polling: 200 },
      )
      const probe = (await handle.jsonValue()) as {
        sourceKind: string
        hwLane: string | null
        ringLastPtsUs: number | null
        spriteBound: boolean
        spriteWidth: number
        spriteHeight: number
        boundFrameKind: string | null
      }

      // ── CLEAN SKIP when the forced lane didn't engage on this machine ───────
      // A forced-but-unadvertised lane (vaapi where libva can't copy-back, any
      // Linux/Windows lane on a Mac, videotoolbox anywhere else) leaves the
      // resolver no candidate → software fallback → probe.hwLane === null → skip.
      test.skip(
        probe.hwLane !== lane,
        `${lane} not engaged on this machine (hwLane=${probe.hwLane}, sourceKind=${probe.sourceKind}) — lane unavailable`,
      )

      // ── The whole point: the forced HW lane engaged and produced the frame ──
      expect(probe.sourceKind).toBe('native-gpu')
      expect(probe.hwLane).toBe(lane)
      expect(probe.spriteBound).toBe(true)
      expect(probe.spriteWidth).toBe(CANVAS.width)
      expect(probe.spriteHeight).toBe(CANVAS.height)
      // …through the RIGHT ingest: 'p10' proves the 10-bit variants really rode
      // the I420P10 transport → TenBitIngest, not a silent NV12 quantize.
      expect(probe.boundFrameKind).toBe(frameKind)

      // ── Rendered preview frame matches an ffmpeg reference (SSIM ≥ the floor) ─
      const ffmpeg = ffmpegBin()
      test.skip(ffmpeg === null, 'ffmpeg not available on PATH (set FFMPEG) — SSIM skipped; lane-engaged proof stands')

      // Capture the LIVE composited preview frame at composition resolution.
      const b64 = (await page.evaluate(
        () => (window as { __weftcutTest: { capturePreviewFramePng(): Promise<string> } }).__weftcutTest.capturePreviewFramePng(),
      )) as string
      const rendered = path.join(OUT_DIR, `rendered-${id}.png`)
      writeFileSync(rendered, Buffer.from(b64, 'base64'))

      // Compare against the SAME source frame decoded by ffmpeg. Robust to a ±1
      // sub-frame PTS-rounding discrepancy between the native seek and ffmpeg's
      // frame index by taking the best of the target frame and its immediate
      // neighbors (a garbage decode matches NONE of the three at the floor).
      const scores: Array<{ idx: number; ssim: number | null }> = []
      for (const idx of [FRAME_IDX - 1, FRAME_IDX, FRAME_IDX + 1].filter((n) => n >= 0)) {
        const reference = path.join(OUT_DIR, `reference-${id}-${idx}.png`)
        execFileSync(ffmpeg!, [
          '-y', '-i', fixture,
          '-vf', `select=eq(n\\,${idx})`,
          '-vsync', '0', '-frames:v', '1', reference,
        ])
        const r = spawnSync(ffmpeg!, [
          '-i', rendered, '-i', reference,
          '-lavfi', '[0:v]format=yuv420p[a];[1:v]format=yuv420p[b];[a][b]ssim',
          '-f', 'null', '-',
        ], { encoding: 'utf8' })
        scores.push({ idx, ssim: parseSsimAll(r.stderr) })
      }
      const best = scores.reduce<{ idx: number; ssim: number }>(
        (acc, s) => (s.ssim != null && s.ssim > acc.ssim ? { idx: s.idx, ssim: s.ssim } : acc),
        { idx: -1, ssim: -1 },
      )
      // eslint-disable-next-line no-console
      console.log(`[preview-hw:${id}] SSIM scores: ${JSON.stringify(scores)} → best=${JSON.stringify(best)} (floor ${ssimFloor})`)
      // The floor is in the message: a bare "below floor" reads as a decode bug,
      // when the first thing to check is whether the floor was ever measured on
      // more than one machine.
      expect(
        best.ssim,
        `SSIM below floor ${ssimFloor}; scores=${JSON.stringify(scores)}`,
      ).toBeGreaterThanOrEqual(ssimFloor)

      // Renderer errors during the run are findings.
      const errs = consoleLines.filter((l) => l.startsWith('[error]') || l.startsWith('[pageerror]'))
      // eslint-disable-next-line no-console
      if (errs.length) console.log(`[preview-hw:${id}] renderer errors during run:\n` + errs.join('\n'))
    } finally {
      // Restore the app-level setting so the run doesn't leave the machine pinned
      // to native (it persists cross-project).
      if (toggledOn) {
        await invokeCmd(page, 'app_settings_set', {
          patch: { decode_engine: 'auto' },
        }).catch(() => {})
      }
      await app.close()
    }
  })
}
