import { MODEL_DEFINITIONS, type ModelBackend, type ModelFamily, type ModelLocalConfig, type ModelProfile, type ModelSettings } from "../shared/inference-models";
import type { SpeechConfigFs } from "./speech-config";
import type { SpeechConfig } from "../shared/speech-config";
import type { VlmConfig } from "../shared/vlm-config";

const BACKENDS: Record<ModelFamily, readonly ModelBackend[]> = {
  speech: ["whisper_cpp", "funasr", "openai"],
  vlm: ["qwen3_vl", "minicpm_v", "byo_endpoint"],
};
export function cleanModelLocal(raw: unknown): ModelLocalConfig {
  const o = raw && typeof raw === "object" ? raw as Record<string, unknown> : {};
  const text = (key: string) => typeof o[key] === "string" ? (o[key] as string).trim() : "";
  const out: ModelLocalConfig = { binary: text("binary"), model: text("model") };
  for (const k of ["tokens", "mmproj", "device"] as const) if (text(k)) out[k] = text(k);
  if (typeof o.threads === "number" && Number.isInteger(o.threads) && o.threads >= 1 && o.threads <= 256) out.threads = o.threads;
  return out;
}
/** A blank path field means "keep the configured file", not "clear it". The
 * settings fields show nothing for a managed file that is not downloaded yet
 * and send back what they showed; clearing a path is not an operation, since a
 * local model cannot run without its files. `device` and `threads` are not
 * paths — blank there still clears them. */
export function withKnownPaths(next: ModelLocalConfig, current?: ModelLocalConfig): ModelLocalConfig {
  if (!current) return next;
  const out = { ...next };
  for (const key of ["binary", "model", "tokens", "mmproj"] as const) {
    const kept = current[key];
    if (!out[key] && kept) out[key] = kept;
  }
  return out;
}
export function freshModelSettings(): ModelSettings {
  return { version: 1, profiles: MODEL_DEFINITIONS.map(d => ({ ...d, artifacts: [...d.artifacts], ...(d.backend === "openai" ? { keyTag: "openai" } : {}) })), active: { speech: null, vlm: null } };
}

function profileFromDisk(raw: unknown): ModelProfile | null {
  if (!raw || typeof raw !== "object") return null;
  const o = raw as Record<string, unknown>;
  const definition = MODEL_DEFINITIONS.find(d => d.id === o.id);
  let p: ModelProfile;
  if (definition) p = { ...definition };
  else {
    if (o.custom !== true || typeof o.id !== "string" || !/^custom-[a-zA-Z0-9_-]+$/.test(o.id) ||
        typeof o.name !== "string" || !o.name.trim() || (o.family !== "speech" && o.family !== "vlm") ||
        !BACKENDS[o.family].includes(o.backend as ModelBackend)) return null;
    const backend = o.backend as ModelBackend;
    p = { id: o.id, name: o.name.trim().slice(0, 120), family: o.family, backend, custom: true,
      locality: backend === "openai" || backend === "byo_endpoint" ? "online" : "local", artifacts: [] };
  }
  if (o.local) p.local = cleanModelLocal(o.local);
  if (o.endpoint && typeof o.endpoint === "object") {
    const ep = o.endpoint as Record<string, unknown>;
    if (typeof ep.url === "string") p.endpoint = { url: ep.url.trim(), model: typeof ep.model === "string" ? ep.model.trim() : "" };
  }
  // Tags are generated by this module/service, never arbitrary references into another profile's secrets.
  p.keyTag = p.custom ? `model-${p.id}` : p.backend === "openai" ? "openai" : p.backend === "byo_endpoint" ? "vlm_endpoint" : undefined;
  if (o.verified === true) p.verified = true;
  if (typeof o.verificationFingerprint === "string") p.verificationFingerprint = o.verificationFingerprint;
  if (o.executionDevice === "cpu" || o.executionDevice === "auto" || o.executionDevice === "fixed") p.executionDevice = o.executionDevice;
  return p;
}

export interface ModelSettingsStore { get(): ModelSettings; set(next: ModelSettings): void }
export function createModelSettingsStore(deps: { fs: SpeechConfigFs; path: string; dir: string; migrate(): ModelSettings }): ModelSettingsStore {
  let cached: ModelSettings | undefined;
  const write = (next: ModelSettings) => {
    deps.fs.mkdirp(deps.dir);
    deps.fs.writeFile(deps.path + ".tmp", JSON.stringify(next, null, 2));
    deps.fs.rename(deps.path + ".tmp", deps.path);
    cached = structuredClone(next);
  };
  return {
    get() {
      if (!cached) {
        let raw: unknown;
        try { if (deps.fs.exists(deps.path)) raw = JSON.parse(deps.fs.readFile(deps.path)); } catch { /* recover from the legacy stores */ }
        const o = raw && typeof raw === "object" ? raw as Record<string, unknown> : {};
        if (o.version === 1 && Array.isArray(o.profiles)) {
          const next = freshModelSettings();
          for (const rawProfile of o.profiles) {
            const p = profileFromDisk(rawProfile);
            if (!p) continue;
            const i = next.profiles.findIndex(x => x.id === p.id);
            if (i < 0) next.profiles.push(p); else next.profiles[i] = p;
          }
          const active = o.active as Record<string, unknown> | undefined;
          for (const family of ["speech", "vlm"] as const) {
            const p = next.profiles.find(p => p.id === active?.[family] && p.family === family);
            next.active[family] = p?.id ?? null;
          }
          cached = next;
        } else write(deps.migrate());
      }
      return structuredClone(cached!);
    },
    set: write,
  };
}

const samePath = (a = "", b = "") => {
  const normalize = (value: string) => process.platform === "win32" ? value.replaceAll("\\", "/").toLowerCase() : value;
  return normalize(a) === normalize(b);
};
export function sameModelFiles(a: ModelLocalConfig, b: ModelLocalConfig): boolean {
  return ["model", "tokens", "mmproj"].every(k => samePath(a[k as keyof ModelLocalConfig] as string, b[k as keyof ModelLocalConfig] as string));
}

/** Resolve the old automatic choice once. Never change a choice when files later disappear. */
export function migrateModelSettings(deps: {
  speech: SpeechConfig; vlm: VlmConfig;
  managedLocal(id: string): ModelLocalConfig;
  exists(path: string): boolean;
  hasKey(tag: string): boolean;
  copyKey(from: string, to: string): void;
}): ModelSettings {
  const next = freshModelSettings();
  const ids = new Map<string, string>();
  for (const family of ["speech", "vlm"] as const) {
    for (const [backend, local] of Object.entries(deps[family].local)) {
      if (!BACKENDS[family].includes(backend as ModelBackend)) continue;
      const builtin = next.profiles.find(p => p.family === family && p.backend === backend);
      let p: ModelProfile;
      if (builtin && sameModelFiles(local, deps.managedLocal(builtin.id))) {
        p = builtin;
        if (JSON.stringify(local) !== JSON.stringify(deps.managedLocal(builtin.id))) p.local = local;
      } else {
        p = { id: `custom-legacy-${backend}`, name: `${builtin?.name ?? backend} (custom)`, family,
          backend: backend as ModelBackend, locality: "local", artifacts: [], custom: true, local };
        next.profiles.push(p);
      }
      ids.set(backend, p.id);
    }
  }
  if (deps.vlm.endpoint) {
    const id = "custom-legacy-endpoint";
    const keyTag = `model-${id}`;
    deps.copyKey("vlm_endpoint", keyTag);
    next.profiles.push({ id, name: deps.vlm.endpoint.model || "Online model", family: "vlm", backend: "byo_endpoint",
      locality: "online", artifacts: [], custom: true, endpoint: { url: deps.vlm.endpoint.url, model: deps.vlm.endpoint.model ?? "" }, keyTag });
    ids.set("byo_endpoint", id);
  }
  ids.set("openai", "openai-whisper");
  const available = (id: string) => {
    const p = next.profiles.find(p => p.id === id)!;
    if (p.backend === "openai") return deps.hasKey("openai");
    if (p.endpoint) return !!p.endpoint.url;
    const lc = p.local ?? deps.managedLocal(id);
    return !!lc.binary && !!lc.model && deps.exists(lc.binary) && deps.exists(lc.model) &&
      (p.backend !== "funasr" || !!lc.tokens && deps.exists(lc.tokens)) &&
      (p.family !== "vlm" || !!lc.mmproj && deps.exists(lc.mmproj));
  };
  for (const family of ["speech", "vlm"] as const) {
    const preferred = deps[family].preferred_engine;
    if (preferred !== "auto") {
      next.active[family] = ids.get(preferred) ?? next.profiles.find(p => p.family === family && p.backend === preferred)?.id ?? null;
    } else {
      const order = family === "speech" ? ["openai", "whisper_cpp", "funasr"] : ["qwen3_vl", "minicpm_v", "byo_endpoint"];
      next.active[family] = order.map(b => ids.get(b)).find((id): id is string => !!id && available(id)) ?? null;
    }
  }
  return next;
}
